version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
    open-pull-requests-limit: 40
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
